// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-hotels.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "B\u1EA1n c\u1EA7n \u0111\u0103ng nh\u1EADp (OAuth) \u0111\u1EC3 d\xF9ng c\xF4ng c\u1EE5 n\xE0y." }],
    isError: true
  };
}

// src/lib/mcp/tools/search-hotels.ts
var search_hotels_default = defineTool({
  name: "search_hotels",
  title: "Search hotels",
  description: "Search Easybooko hotels by destination, property type, price range and minimum rating. Prices are in VND per night.",
  inputSchema: {
    destination: z.string().trim().optional().describe("City or location, e.g. 'Da Nang'."),
    property_type: z.enum(["hotel", "apartment", "resort", "villa"]).optional().describe("Accommodation type filter."),
    min_price: z.number().nonnegative().optional().describe("Minimum price per night in VND."),
    max_price: z.number().positive().optional().describe("Maximum price per night in VND."),
    min_rating: z.number().min(0).max(5).optional().describe("Minimum star rating."),
    limit: z.number().int().min(1).max(25).default(10).describe("Max hotels to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ destination, property_type, min_price, max_price, min_rating, limit }) => {
    let query = supabaseAnon().from("hotels").select("id,name,location,property_type,price_per_night,rating,amenities,description").order("rating", { ascending: false }).limit(limit ?? 10);
    if (destination) query = query.ilike("location", `%${destination}%`);
    if (property_type) query = query.eq("property_type", property_type);
    if (min_price !== void 0) query = query.gte("price_per_night", min_price);
    if (max_price !== void 0) query = query.lte("price_per_night", max_price);
    if (min_rating !== void 0) query = query.gte("rating", min_rating);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length)
      return { content: [{ type: "text", text: "No hotels matched those filters." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { hotels: data }
    };
  }
});

// src/lib/mcp/tools/get-hotel.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_hotel_default = defineTool2({
  name: "get_hotel",
  title: "Get hotel details",
  description: "Get full details for one Easybooko hotel including amenities and its room types with prices (VND) and quantity.",
  inputSchema: {
    hotel_id: z2.string().uuid().optional().describe("Hotel id."),
    name: z2.string().trim().min(2).optional().describe("Hotel name (partial match) if id is unknown.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ hotel_id, name }) => {
    if (!hotel_id && !name)
      return { content: [{ type: "text", text: "Provide hotel_id or name." }], isError: true };
    const supabase = supabaseAnon();
    let query = supabase.from("hotels").select("id,name,location,property_type,description,price_per_night,rating,amenities,images").limit(1);
    query = hotel_id ? query.eq("id", hotel_id) : query.ilike("name", `%${name}%`);
    const { data: hotel, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!hotel) return { content: [{ type: "text", text: "Hotel not found." }], isError: true };
    const { data: rooms, error: roomsError } = await supabase.from("rooms").select("id,type,price,quantity,available").eq("hotel_id", hotel.id).order("price");
    if (roomsError)
      return { content: [{ type: "text", text: roomsError.message }], isError: true };
    const result = { ...hotel, rooms: rooms ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { hotel: result }
    };
  }
});

// src/lib/mcp/tools/check-room-availability.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var check_room_availability_default = defineTool3({
  name: "check_room_availability",
  title: "Check room availability",
  description: "Check how many rooms of each type are still available at a hotel for a date range (check-out day is free for a new check-in).",
  inputSchema: {
    hotel_id: z3.string().uuid().describe("Hotel id."),
    check_in: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Check-in date (YYYY-MM-DD)."),
    check_out: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Check-out date (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ hotel_id, check_in, check_out }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    if (check_in >= check_out)
      return { content: [{ type: "text", text: "check_out must be after check_in." }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data: rooms, error } = await supabase.from("rooms").select("id,type,price,quantity,available").eq("hotel_id", hotel_id).order("price");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!rooms?.length)
      return { content: [{ type: "text", text: "No rooms found for that hotel." }], isError: true };
    const { data: counts, error: rpcError } = await supabase.rpc("get_room_overlap_counts", {
      _hotel_id: hotel_id,
      _check_in: check_in,
      _check_out: check_out
    });
    if (rpcError) return { content: [{ type: "text", text: rpcError.message }], isError: true };
    const booked = /* @__PURE__ */ new Map();
    for (const row of counts ?? []) {
      booked.set(row.room_id, Number(row.booked_count));
    }
    const availability = rooms.map((r) => {
      const used = booked.get(r.id) ?? 0;
      const remaining = r.available ? Math.max(0, (r.quantity ?? 1) - used) : 0;
      return { room_id: r.id, type: r.type, price: r.price, remaining };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(availability, null, 2) }],
      structuredContent: { check_in, check_out, availability }
    };
  }
});

// src/lib/mcp/tools/list-my-bookings.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_my_bookings_default = defineTool4({
  name: "list_my_bookings",
  title: "List my bookings",
  description: "List the signed-in user's Easybooko bookings with hotel, room, dates, total (VND) and status.",
  inputSchema: {
    status: z4.enum(["pending", "confirmed", "cancelled", "rejected"]).optional().describe("Optional status filter."),
    limit: z4.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("bookings").select("id,check_in,check_out,total_price,status,created_at,hotel_id,room_id").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data: bookings, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!bookings?.length)
      return { content: [{ type: "text", text: "B\u1EA1n ch\u01B0a c\xF3 \u0111\u01A1n \u0111\u1EB7t ph\xF2ng n\xE0o." }] };
    const hotelIds = [...new Set(bookings.map((b) => b.hotel_id))];
    const roomIds = [...new Set(bookings.map((b) => b.room_id).filter(Boolean))];
    const [{ data: hotels }, { data: rooms }] = await Promise.all([
      supabase.from("hotels").select("id,name,location").in("id", hotelIds),
      roomIds.length ? supabase.from("rooms").select("id,type,price").in("id", roomIds) : Promise.resolve({ data: [] })
    ]);
    const enriched = bookings.map((b) => ({
      ...b,
      hotel: hotels?.find((h) => h.id === b.hotel_id) ?? null,
      room: rooms?.find((r) => r.id === b.room_id) ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(enriched, null, 2) }],
      structuredContent: { bookings: enriched }
    };
  }
});

// src/lib/mcp/tools/manage-wishlist.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var manage_wishlist_default = defineTool5({
  name: "manage_wishlist",
  title: "Manage wishlist",
  description: "List, add to, or remove hotels from the signed-in user's Easybooko wishlist.",
  inputSchema: {
    action: z5.enum(["list", "add", "remove"]).describe("Operation to perform."),
    hotel_id: z5.string().uuid().optional().describe("Hotel id \u2014 required for add and remove.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ action, hotel_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    if (action !== "list" && !hotel_id)
      return { content: [{ type: "text", text: "hotel_id is required for this action." }], isError: true };
    if (action === "add") {
      const { error: error2 } = await supabase.from("wishlists").insert({ user_id: userId, hotel_id });
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
    }
    if (action === "remove") {
      const { error: error2 } = await supabase.from("wishlists").delete().eq("user_id", userId).eq("hotel_id", hotel_id);
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
    }
    const { data, error } = await supabase.from("wishlists").select("hotel_id,created_at").eq("user_id", userId).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const ids = (data ?? []).map((w) => w.hotel_id);
    const { data: hotels } = ids.length ? await supabase.from("hotels").select("id,name,location,price_per_night,rating").in("id", ids) : { data: [] };
    return {
      content: [{ type: "text", text: JSON.stringify(hotels ?? [], null, 2) }],
      structuredContent: { wishlist: hotels ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yodsepgwyfyekmpqvosw";
var mcp_default = defineMcp({
  name: "easybooko",
  title: "Easybooko",
  version: "0.1.0",
  instructions: "Tools for Easybooko, a Vietnam-focused hotel booking app. Use `search_hotels` and `get_hotel` to browse stays (prices in VND), `check_room_availability` for a date range, `list_my_bookings` for the signed-in user's reservations, and `manage_wishlist` to list/add/remove saved hotels.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_hotels_default,
    get_hotel_default,
    check_room_availability_default,
    list_my_bookings_default,
    manage_wishlist_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
